---
- name: Debug startup
  ansible.builtin.debug:
    msg: this from webitel

- name: Add PostgreSQL apt-key
  ansible.builtin.apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Add PostgreSQL repository into sources list
  ansible.builtin.apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt/ {{ hostvars[inventory_hostname].ansible_distribution_release }}-pgdg main
    state: present
    filename: postgresql

- name: Add TimescaleDB apt-key
  ansible.builtin.apt_key:
    url: https://packagecloud.io/timescale/timescaledb/gpgkey
    state: present

- name: Add TimescaleDB repository into sources list
  ansible.builtin.apt_repository:
    repo: deb https://packagecloud.io/timescale/timescaledb/debian/ {{ hostvars[inventory_hostname].ansible_distribution_release }} main
    state: present
    filename: timescaledb

- name: Update repositories cache and install PostgreSQL 14 and timescaledb packages
  ansible.builtin.apt:
    pkg:
      - postgresql-14
      - timescaledb-2-postgresql-14
    update_cache: true

- name: Execute timescaledb-tune
  ansible.builtin.command: timescaledb-tune --quiet --yes
  register: tsdbtune
  changed_when: tsdbtune.rc != 0

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  notify: restart postgresql
  when:
    - systemd_unit is changed

- name: Restart PostgreSQL on Linux
  ansible.builtin.service:
    name: postgresql
    state: restarted

- name: Enable PostgreSQL at startup
  ansible.builtin.systemd:
    name: postgresql
    enabled: true

- name: Create "testdb" user, set password, grant privs
  community.postgresql.postgresql_user:
    name: testdb
    password: testit
    role_attr_flags: SUPERUSER
  become_user: postgres

- name: Create a new database with name "testit"
  community.postgresql.postgresql_db:
    name: testit
    owner: testdb
  register: create_db
  become_user: postgres

- name: Creates a cron file under /etc/cron.d
  ansible.builtin.cron:
    name: psql daily script
    minute: "4"
    hour: "4"
    user: postgres
    job: "psql testtb < /dev/null"
    cron_file: ansible_psql-database_helper
