---
- name: Converge
  hosts: instance
  tasks:
    - name: Update apt-cache for good measure
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

- name: Import main playbook
  import_playbook: ../../../../database.yml
