dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  # yamllint
platforms:
  - name: moleculedb
    image: "registry.gitlab.com/aussielunix/ansible/molecule-containers/${MOLECULE_DISTRO:-debian:bullseye}"
    privileged: true  # systemd needs this :( (docker runs full root on host)
    pre_build_image: true  # not from a local Dockerfile build
    override_command: false
    tmpfs:
      - /run
      - /tmp
provisioner:
  name: ansible
  log: ${MOLECULE_ANSIBLE_LOG:-true}
  env:
    ANSIBLE_VERBOSITY: ${MOLECULE_ANSIBLE_VERBOSITY:-0}
verifier:
  name: ansible
